# Generated by Django 3.2 on 2021-06-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='destination',
            new_name='designation',
        ),
    ]
